### ISSUE TITLE
Suggest readme.txt be more explicit about running 'pforth -i system.fth'

### ISSUE THREAD

**Issue by MaxBarraclough** [philburk/pforth#106]
I suggest the readme.txt file be more explicit about how to build the dictionary file (`pforth -i system.fth`), as it's currently not very 'discoverable' for newcomers. Personally I googled it and found my way to [this site](https://code.google.com/archive/p/pforth/wikis/HowToCompile.wiki), which spells out the steps.

**Comment by jgerrish** [comment]
Hey.  Thank you for this project.  I was able to build it and work with pforth, great experience.  I used cmake for the build, which is where I came across initial issues with the dictionary file build.

Updating the readme.txt is one approach here, modifying CMakeLists.txt to support building in a non-root directory may also work.  I could submit a PR for that if you wanted.

Have a great weekend.

**Comment by mschwartz** [comment]
If I wanted to install pForth in /usr/local/bin, where is pForth going to find the dictionary file?  Where is it going to write it?  Perhaps env variables?

I think it might be useful to be able to run a turnkey forth application from any directory…

is shebang supported?  Something like this would work:

#!/usr/local/bin/pforth -I path-to-application

Just thinking out loud here…

**Comment by philburk** [comment]
@mscwartz - I created a new Issue for your topic. 3146
This topic is about compiling the original Forth code.
Your topic is about loading pre-compiled dictionary files.

**Comment by philburk** [comment]
I am closing this because the docs have been modified.
If jgerrish wants to submit a modified CMake file then that would be most welcome.
