### ISSUE TITLE
Link to documentation broken?

### ISSUE THREAD

**Issue by rmoritz** [philburk/pforth#115]
I can't access the documentation at https://www.softsynth.com/pforth/. In fact, I can't even ping that domain. Since I can't find the docs here on GitHub, is it hosted anywhere else?

**Comment by bill-raynor** [comment]
Same problem, but the [wayback archive](https://web.archive.org/web/20210730081348/http://softsynth.com/pforth/pf_ref.php) still works as of 2022-05-05.

**Comment by philburk** [comment]
Note that HTTPS is not supported.

Also our server was down because a drive became unmounted.

This should now be working.
http://www.softsynth.com/pforth/
