### ISSUE TITLE
PForth + FPGA Marketing

### ISSUE THREAD

**Issue by PythonLinks** [philburk/pforth#157]
Thank you so much for porting pForth to the Pico-ice, and for integrating the Pico-ICE SDK with pForth.  Now pForth can be used with the ICE40 FPGA. 

Sadly I think everyone forgot about it.  So I will try to post occasionally in the pico-ice discord server about it.  A logo would be helpful. 

Even better would be if someone had a pForth application that needed acceleration with an FPGA.

**Comment by znmeb** [comment]
When was pforth ported to the pico-ice? I was attempting to port it to the regular Pico a year or so ago but I never got the port to work. Are you thinking of [flagxor/ueforth?](https://github.com/flagxor/ueforth/)

**Comment by PythonLinks** [comment]
OOPS.   I searched for pforth, and google gave me this page.  
https://eforth.appspot.com/pico-ice.html

So ueForth, not pForth.   Sorry. 

I stand corrected.
