### ISSUE TITLE
Unix Makefile fails on macOS

### ISSUE THREAD

**Issue by profburke** [philburk/pforth#166]
cd platforms/unix
make test

EXPECT build to work

ACTUAL
c99  -x c -O2 --std=c89  -fsigned-char  -fno-builtin  -fno-unroll-loops  -pedantic  -Wcast-qual  -Wall  -Wwrite-strings  -Winline   -Wmissing-prototypes  -Wmissing-declarations  -g -I. -DPF_SUPPORT_FP -D_DEFAULT_SOURCE -D_GNU_SOURCE -c -o pf_cglue.o ../../csrc/pf_cglue.c
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c99: illegal option -- x
usage: c99 [-cEgs] [-D name[=value]] [-I directory] ... [-L directory] ...
       [-o outfile] [-O optlevel] [-U name]... [-W 64] operand ...
make: *** [Makefile:77: pf_cglue.o] Error 1

Note: I tried this with the current released version of Xcode (15.4) as well as the latest beta (16 beta 4). Same error in both cases.

Solution: setting CC=clang solves the issue; i.e. pforth builds with no problem.

I can open a pull request with changes to the Makefile that conditionally uses clang based on detecting the operating system.

**Comment by profburke** [comment]
I've gone ahead and added a PR. If you are generally in favor, but want some changes, please let me know.

Regards,

Matt

**Comment by philburk** [comment]
@profburke - Thanks so much for the clang fix.  I merged your change. It seems to work fine.

**Comment by profburke** [comment]
You're welcome. And thanks for all the work you do on pforth. I'm really excited to use it to get back into Forth programming.
