### ISSUE TITLE
immediate value problem

### ISSUE THREAD

**Issue by ellerh** [philburk/pforth#20]
pForth has a problem with this test from the [forth2012-test-suite](https://github.com/gerryjackson/forth2012-test-suite):
```
PForth V27-LE/64, built Dec 17 2016 18:35:01
pForth loading dictionary from file /scratch/forth/pforth/build/unix/pforth.dic
     File format version is 9 
     Name space size = 120000 
     Code space size = 300000 
     Entry Point     = 0 
     Cell Size       = 8 
     Little  Endian Dictionary

123 VALUE VAL3 IMMEDIATE    ok
Stack<10> 
: VD3 VAL3 LITERAL ; Stack<10> UNDERFLOW!
THROW code = -257 
Stack depth changed between : and ; . Probably unbalanced conditional!
```

**Comment by philburk** [comment]
LITERAL seems to be working fine.

I think the problem is that all VALUE words are defined as IMMEDIATE.
Their immediate effect is to compile a reference to the value's body followed by a @. This is an optimization that is apparently non-standard.

**Comment by ruv** [comment]
It is better to leave such optimization work for `COMPILE,` word, or achieve via `NAME>COMPILE`.

**Comment by philburk** [comment]
@ellerh - What do you think of the possible fix in #79

**Comment by ellerh** [comment]
Looks good to me.
Of course, it wouldn't hurt to add this test to the testsuite ...

**Comment by philburk** [comment]
Good idea. I added the test. Next step is to make TRAVIS CI fail when the tests fail.
