### ISSUE TITLE
Catch duplicates throw code under certain conditons

### ISSUE THREAD

**Issue by FrankRuben** [philburk/pforth#37]
Hi,
I have a surprising phenomenon best explained by two code samples.
This one works as expected:

```
: foo-throw -888 .s throw ;
: foo-catch ['] foo-throw catch .s ;
0sp foo-catch
```
and yields:
```
Stack<10> -888
Stack<10> -888
```

When I complicate the invocation by passing another xt to the called word (in the real code I'm doing this for a reason), I will receive the throw code twice on the catch side, like so:
```
: bar-doit  ( -- )    ." doing it!" cr ;
: bar-throw ( xt -- ) execute -999 .s throw ;
: bar-catch ( -- )    ['] bar-doit  ['] bar-throw  catch .s ;
0sp bar-catch
```
which yields:
```
doing it!
Stack<10> -999
Stack<10> -999 -999
```

There is a fix around exception handling in [Helmut Eller's fork](http://www.google.com/url?q=http%3A%2F%2Fgithub.com%2Fellerh%2Fpforth%2Fcommit%2F04dbf79ab9bde0e3bcd088f551ce1944bdbdade1&sa=D&sntz=1&usg=AFQjCNFyVvfFNhesCmK11eA8WHY5HLUunA) but that doesn't help for the case mentioned here.

Thanks for taking a look, Frank

**Comment by ellerh** [comment]
I think the result of BAR-CATCH is not well defined.  CATCH should restore the stack pointer then push the throw code. So there should be two items on the stack and the top-of-stack item should be -999.  But  it is not clear what the second stack item should be.  As BAR-THROW takes the XT from the stack, we have a kind of stack underflow situation and the content of the stack above the stack pointer is not well defined. 

As far as I can tell SwiftForth, VfxForth, cForth, GForth 0.7.9 all produce -999 twice.
GForth  0.7.2 is a bit different: it produces `' bar-doit -999`

**Comment by FrankRuben** [comment]
The code above is only to show the issue, that's why I have the `.s` after the catch, not because it's in the contract of `foo-catch` or `bar-catch`. 
And I don't understand the reason for a stack underflow in `bar-throw`: it's not expecting `bar-doit` to leave something on the stack, so stack is supposed to be empty after the `execute`, then the throw-code is pushed and thrown.
I only have GForth installed and got the expected result as you did, so I assumed that this was to expected. But as you posted the results from others Forths to also match the pforth result, it seems that my test case is less clear-cut as I expected.
So thanks a lot for your support!
