### ISSUE TITLE
Problems while compiling at Windows

### ISSUE THREAD

**Issue by HipercubesHunter11** [philburk/pforth#51]
I exported the protect to Code::Blocks and i tried to compile it. It stops before building the executable 'cuz it doesn't find some '-l*.lib' libraries. Can you please pass me a makefile for the mingw32-make.exe and mingw32-gcc.exe that Code::Blocks has?

**Comment by catb0t** [comment]
Which libraries are listed as missing?

**Comment by HipercubesHunter11** [comment]
-l                        .lib
winmm
comctl32
kernel32
user32
gdi32
winspool
comdlg32
advapi32
shell32
ole32
oleaut32
uuid
odbc32
odbccp32

**Comment by philburk** [comment]
@letoh - Thanks for that script. I am not familiar with CodeBLocks or MinGW.
So please submit a Pull-Request with that change.

**Comment by philburk** [comment]
Closing as obsolete.
Please try the new CMake support.
