### ISSUE TITLE
static dictionary never loads -- infinite loop

### ISSUE THREAD

**Issue by jbdatko** [philburk/pforth#67]
I have compiled and run pforth on a Microblaze soft-core on a Xilinx 7 FPGA. I followed the embedded instructions I think and set the appropriate flags, with the exception of the IO one as I just hacked my IO functions in a .c file versus making a separate one.

I SDAD the dictionary from an x86 and added it. Inspecting memory in the debugger, it appears to be assigned to the `dic_HeaderBase` etc...

However in `FindSpecialXTs` the code never returns from trying to find `(QUIT)`. In `ffFindNFA`, `Searching` remains `TRUE` and thus, never exits. I tried debugging further but I'm not familiar with the code so I think I'm at my limit here.

The first iteration of the do loop, the `NameField` variable is `\004;;;;`, the second time, it's `p` the third it appears to be garbage. After that it is stuck in this loop.

The output of the terminal is below.

```
DBG: PForth V28-LE/32, built Sep  9 2019 17:22:25 (static)

static dic name size = 48940


DBG: static dic code size = 124956

DBG: pfAllocRawMem()

DBG: pfAllocRawMem()

DBG: pfAllocRawMem()
```

**Comment by philburk** [comment]
The x86 is Little-Endian and I think the Microblaze is Big-Endian.
That might be the issue.
Did you define PF_BIG_ENDIAN_DIC
http://www.softsynth.com/pforth/pf_ref.php#Compiling-pForth

**Comment by jbdatko** [comment]
Thanks Phil, I'll take a look. Microblaze is configurable endianness, I'm pretty sure it was set to LE, but I'll check.

Would a 64 bit generated dictionary affect running on a 32 bit system?

I also tried this on an ARM 32 platform where I thought I would have more success. I generated the dictionary from the host, copied the static dictionary, but same issue.

What _does_ work is to start forth on the embedded system with _no_ dictionary. This requires some hacking of things to make pforth want to initialize the dictionary w/o FILEIO, but it does work. But to date, I've been unsuccessful in bringing over a static dictionary. In the end, this may be fine as the default dictionary is a bit "feature-full" for a no-OS embedded system, but I was just surprised by this behavior.

**Comment by philburk** [comment]
> Would a 64 bit generated dictionary affect running on a 32 bit system?

Yes, they are incompatible. The C code should check for that but may not.

> This requires some hacking of things to make pforth want to initialize the dictionary w/o FILEIO, but it does work.

How do you "initialize the dictionary" without compiling from files, loading a dictionary file, or building with a static dictionary?

**Comment by philburk** [comment]
I tried loading a 64-bit dictionary with a 32-bit pforth executable and got:

    Error in pfLoadDictionary - cell size mismatch between .dic file and code

I also tried a 32-bit dic and 64-bit code and got the same error.

I am closing this because I think the problem was using a 64-bit dictionary on a 32-bit system.

You can compile a 32-bit pforth using

    cd platforms/unix
    make WIDTHOPT=-m32

If you have a missing bits file you may need gcc-multilib.
See https://www.geeksforgeeks.org/compile-32-bit-program-64-bit-gcc-c-c/

**Comment by jbdatko** [comment]
Thanks for trying! I for sure tried 64->32, so this is probably it. I have a 32-bit arm with linux on it and I can build the dic there and try it.

Thanks again for the help.
