### ISSUE TITLE
Tag for V28 release

### ISSUE THREAD

**Issue by SeekingMeaning** [philburk/pforth#73]
https://github.com/philburk/pforth/releases

Commit: d71efe1792a1414a5b102ae8e69f3913c70aa8b0

**Comment by philburk** [comment]
@SeekingMeaning - How do I tag an old commit?

BTW, I am getting ready to release V29.

**Comment by philburk** [comment]
I tagged V28. I called it "v1.28.0" so that the versioning would be monotonic.

https://github.com/philburk/pforth/releases/tag/v1.28.0
