### ISSUE TITLE
OSS license for the repo?

### ISSUE THREAD

**Issue by chenrui333** [philburk/pforth#74]
It looks like the repo does not have OSS license.

relates to #73
relates to Homebrew/homebrew-core#57250

**Comment by SeekingMeaning** [comment]
> Public Domain software may come with the rights delivered by those “four freedoms”, but you can’t be sure. It will depend where the software was written, where you are located, who the author is and where the people you are sharing the software with are located.
>
> &mdash; ["Public Domain Is Not Open Source", Open Source Initiative](https://opensource.org/node/878)

> The [Zero Clause BSD license](https://en.wikipedia.org/wiki/BSD_licenses#0-clause_license_(%22Zero_Clause_BSD%22)) removes half a sentence from the OpenBSD template license, leaving only an unconditional grant of rights and a warranty disclaimer. It is listed by the Software Package Data Exchange as the Zero Clause BSD license, with the SPDX identifier "0BSD." It was first used by Rob Landley in Toybox, and is the only OSI-approved public domain equivalent license.
>
> &mdash; ["Public-domain-equivalent license", Wikipedia](https://en.wikipedia.org/wiki/Public-domain-equivalent_license)

**Comment by philburk** [comment]
Fixed in #75
