### ISSUE TITLE
no longer builds with make 4.3 on Linux, bad rules in Makefile

### ISSUE THREAD

**Issue by mschwartz** [philburk/pforth#76]
Hey @philburk ,

pforth builds on macos but not linux, using the build/unix directory.  it used to work on linux, but no more.

It seems VPATH is not being honored by gnu make 4.3 for the .c files.  This is a fresh clone of the repo:

```
(build/unix)> make all
make: *** No rule to make target 'pf_cglue.o', needed by 'pforth'.  Stop.
```

Output of make -d

[pforth_makeout.txt](https://github.com/philburk/pforth/files/5177140/pforth_makeout.txt)

**Comment by mschwartz** [comment]
It definitely doesn’t build with 4.3.

The .txt file In my post shows it tries vpath for the .h files but not the .c ones.

Bummer 😒

**Comment by philburk** [comment]
Do you think I may be doing something wrong in the Makefile and now make 4.3 is catching it?
Or is make 4.3 broken in some way?
I am doing such simple things I cannot imagine make is broken.

That vfx forth sounds cool. I was worried pForth would be too slow because it uses C instead of native assembly. So I did a benchmark and it was about 1000 times faster than JForth. So I stopped worrying about speed. :-)

**Comment by mschwartz** [comment]
Your CPU is 1000X faster than the 68000 😀  pFirth’s strengths are it’s portable and the clever words you brought over from jForth.

I think the makefile is straightforward, but 4.3 isn’t working like make has all along.  I have built pforth on this machine before.  The update to make seems to be the issue.

I would think you want new users to have it build first thing...

I could easily rearrange the directory structure and make it work without vpath, but it is your design and the fix may be simpler than my taking a hatchet to it.  LOL.

**Comment by mschwartz** [comment]
Also, make is ridiculously harder than it should be!

A simple project can be built with more obvious sh scripts.

Or there’s cmake.  Or maybe something like grunt using google’s own v8.

**Comment by philburk** [comment]
Yes, sh scripts are good. PForth is pretty simple.

Please take a look at #72 , which adds cmake support.

**Comment by mschwartz** [comment]
Try it in a VM?

**Comment by mschwartz** [comment]
Ah, you know what?  You can use Docker to build it.

https://hub.docker.com/_/gcc

**Comment by mschwartz** [comment]
I’ve been working on an AmigaOS inspired hobby OS.  Rather than build a cross compiler, I used a Docker container.  The build instructions are: install Docker && ./build.sh

The build.sh script does the Docker voodoo.

It’s nice because you can pin the versions of gcc and make with the chosen container image, plus it builds in Windows, Mac, and *nix.

**Comment by mschwartz** [comment]
https://www.reddit.com/r/osdev/comments/imnii1/amos_work_in_progress/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by philburk** [comment]
Custom OS! That sounds like way too much fun.

> Try it in a VM?

My Ubuntu Linux is in a VM on a Mac. It has make 4.1

> I would think you want new users to have it build first thing

That is definitely the goal. 

> I could easily rearrange the directory structure and make it work without vpath

Can you describe that briefly? I would like to use Make even if I have to forego VPATH.

Or can you file a bug at:
    https://www.gnu.org/software/make/manual/make.html#Bugs

**Comment by mschwartz** [comment]
Install Arch Linux in a new VM.  Rolling distribution, so it will update to latest make.

I would just have Makefile.unix, Makefile.mac, etc., in the top directory and use -I for include path.

The Makefile for my OS finds all the .cpp in directories below (*/** or specific/*) the git workspace root and compiles them into obj/.  It makes the tree structures as it compiles.  It also makes dependency files in obj/ so it will only build .c files that change or depend on .h that change.

OS repo:  https://github.com/mschwartz/amos

Makefile: https://github.com/mschwartz/amos/blob/master/Makefile

Makefile include files from mk/ to set up CFLAGS and build targets.

The build.sh script generates the Docker container with gcc in it (if need be) and runs the make inside that.

**Comment by mschwartz** [comment]
So something like common/ and Unix/ and Mac/ and Makefile for each.

Custom files go in Unix/custom, etc.

**Comment by mschwartz** [comment]
Typing on my iPad.. my grammar is rough and typos are autocorrect!  😉

**Comment by philburk** [comment]
@mschwartz - does #80 fix this issue for you?

**Comment by philburk** [comment]
This was auto-closed by GitHub. But we still need to verify that #80 is a fix for this.

**Comment by mschwartz** [comment]
I looked at the PR you merged.  I am reasonably sure it has no relation to the bug I reported.  Looks like makefile is still relying on vpath.  I can try to compile master tomorrow.

**Comment by philburk** [comment]
@letoh wrote that PR [#80] "should fix #76". But I don't understand how. 

The Makefile is still using VPATH but the rules have been changed. So it seems possible.

**Comment by mschwartz** [comment]
Wow, it does build.

And super fast 👍

**Comment by mschwartz** [comment]
This needs more testing on my end.  Tomorrow.

I will close this when I confirm on a couple more machines I have.

**Comment by philburk** [comment]
Great! Thanks mschwarz for testing this. Close when ready.

And thanks letoh for the mysterious fix.

**Comment by mschwartz** [comment]
Looking again at the PR, I think it's changed the dependencies a tad.  Just enough, it seems.

Otherwise, I found the code and the Makefile(s) to be professional.

**Comment by letoh** [comment]
> 
> 
> @letoh wrote that PR [#80] "should fix #76". But I don't understand how.

@philburk Thank you for verifying the PR :-)

The root cause of this issue is that GNU make does something implicitly to the suffix rules but POSIX make doesn't. For example, when a POSIX make see a rule:
```makefile
.c.o:
    $(CC) -c -o $@ $<
```
it knows the rule is a suffix rule and does the job as we expected. But when it see anything in the prerequisite list:
```makefile
.c.o: some prerequisites
    $(CC) -c -o $@ $<
```
it only knows that we need a file `.c.o` that is generated from the leftmost file in the `some prerequisites`, but doesn't know any rule about pf_cglue.o (and all the other objs).

Let's see the actual rule that make will use:
```bash
make -p | grep "\.c\.o" -A 6
```

and you will get the result:
```
.c.o: ../../csrc/pf_all.h ../../csrc/pf_cglue.h ../../csrc/pf_clib.h ../../csrc/pf_core.h ../../csrc/pf_float.h ../../csrc/pf_guts.h ../../csrc/pf_host.h ../../csrc/pf_inc1.h ../../csrc/pf_io.h ../../csrc/pf_mem.h ../../csrc/pf_save.h ../../csrc/pf_text.h ../../csrc/pf_types.h ../../csrc/pf_win32.h ../../csrc/pf_words.h ../../csrc/pfcompfp.h ../../csrc/pfcompil.h ../../csrc/pfdicdat_arm.h ../../csrc/pfinnrfp.h ../../csrc/pforth.h
#  Implicit rule search has not been done.
#  Modification time never checked.
#  File has not been updated.
#  recipe to execute (from 'Makefile', line 77):
    $(COMPILE) -c -o $@ $<
```

it shows that the builtin rule has been overwritten, and the recipe from the new-defined rule says that it (only) knows how to generate the file `.c.o` file from `../../csrc/pf_all.h`. You can confirm this by passing `.c.o` as the target explicitly:
```bash
make .c.o
```

That is why you just get the following message when you try to build all with make 4.3:
```
make: *** No rule to make target 'pf_cglue.o', needed by 'pforth'.  Stop.
```

Some rules for `pf_cglue.o` are gone.


How about the make before version 4.3? It will generate missing pattern rules from the suffix rules:
```bash
make -p | grep "\.eo" -A 6
```

and you will get two rules for bulding *.eo:
```makefile
%.eo: %.c
#  recipe to execute (from `Makefile', line 80):
    $(COMPILE) $(EMBCCOPTS) -c -o $@ $<

.c.eo: ../../csrc/pf_all.h ...
#  Implicit rule search has not been done.
#  Modification time never checked.
#  File has not been updated.
#  recipe to execute (from `Makefile', line 80):
    $(COMPILE) $(EMBCCOPTS) -c -o $@ $<
```

even if you didn't write any pattern rules, the old GNU make generate one for you implicitly. So you can bulid all you want by the generated pattern rules. As for the second rule, just like I explained earlier, is just a simple rule for building a file `.c.eo` from `../../csrc/pf_all.h`.

The PR #80 just does what the old GNU make does and remove useless rules.

> 
> The Makefile is still using VPATH but the rules have been changed. So it seems possible.

VPATH works well (at least in this issue), though it might bring some problems in cross compilation.

**Comment by letoh** [comment]
> 
> 
> Looking again at the PR, I think it's changed the dependencies a tad. Just enough, it seems.

In fact, the PR changes nothing, it just make the building rules explicit (and remove some useless rules).

**Comment by letoh** [comment]
@philburk There is one thing I forgot to say: the PR only fix the unix build, so this issue might still effect other crossbuilds. I don't have the environment for those crossbuilds, so I leave them untouched. If someone reports the same issue, you can fix it just as I showed in the PR :-)

**Comment by mschwartz** [comment]
The makefiles before the PR merge worked with make < version 4.3, but not with version 4.3.

**Comment by mschwartz** [comment]
Works in 4.3 on linux and Mac and WSL.

I suggest testing the cross compilation variants and apply the same changes to those, if need be.

**Comment by mschwartz** [comment]
I wanted to say thanks for this.  It's working great.  I did have to edit my own custom Makefile, to make the same fixes.

As a side note, I have a .ccls file in my fork of the repo.  It works with lsp in the editor (works in VS Code, vim, emacs, etc.).  It is basically one compiler switch per line.  So something like -I ...  or -D...  makes it so the lsp error checking on the fly knows about the include paths and -D defines.

https://github.com/MaskRay/ccls

Each of us might have our own .ccls, so I'm not sure you'd want it in the repo.  It's just a tip.
