### ISSUE TITLE
Delete key is same as backspace

### ISSUE THREAD

**Issue by vuokko** [philburk/pforth#8]
in history.fth
        ASCII_BACKSPACE OF kh.backspace ENDOF
        ASCII_DELETE    OF kh.backspace ENDOF
Should be
        ASCII_DELETE    OF kh.delete ENDOF

And in the end:
: AUTO.TERM
	history.off
	auto.init
;
should have auto.term, not auto.init

**Comment by philburk** [comment]
The call to auto.init is definitely a bug! Thanks for reporting that.

The DELETE key behavior is complicated. On my Mac laptop, there is only the "delete" key. It works like backspace when editing text in other applications. If I make the change then the pForth "Delete" key will behave very oddly on Mac laptops.

**Comment by vuokko** [comment]
OK. It seems that OS X send 0x7f (delete) with delete key.
With FN+delete I get 
key key key key    ok
Stack<16> 1B 5B 33 7E ( ESC  [ 3 DEL ) http://www.naurtech.com/wiki/wiki.php?n=Main.KeymapDefaultVTSeq Which seems to be "Remove"
There is in settings advanced delete sends Ctrl-H which is 0x08 (BS) At least this is case on my US- layout KB which is set to Finnish mapping.

But then again I'm not able to send DEL unless the "Remove" is implemented.

**Comment by philburk** [comment]
I fixed the auto.init in history.fth. Thanks.

But I don't think I will change DELETE because it will break BACKSPACE behavior on lots of machine.
