### ISSUE TITLE
unit test fails for S", need dual storage

### ISSUE THREAD

**Issue by philburk** [philburk/pforth#81]
I think that S" should use two storage areas to avoid collisions.

INCORRECT RESULT: T{ S" abcd"  S" 1234" SSQ13  S= ROT ROT SSQ12 S= -> TRUE TRUE }T

**Comment by nobodxbodon** [comment]
Just got this failure message when "make test" under Mac.
So this is because there's only one hard drive in the system?

**Comment by catb0t** [comment]
> Just got this failure message when "make test" under Mac. So this is because there's only one hard drive in the system?

No, it is referring to memory storage areas for these strings `S" abcd"`, etc. Sounds like they are currently sharing memory and overwrite eachother's memory when they are used within a word.

**Comment by philburk** [comment]
The current S" passes the tests for ANS Forth.
https://forth-standard.org/standard/core/Sq

So I don't think it is worth fixing this.
I substituted the old tests with the new test from ANS.
