### ISSUE TITLE
Missing ANS standard word: S\"

### ISSUE THREAD

**Issue by MaxBarraclough** [philburk/pforth#95]
pForth defines the `S"` word, but not the related `S\"` word, [which](http://www.complang.tuwien.ac.at/forth/ansforth-cvs/documents/html3/core/Seq.html) is [part](https://forth-standard.org/standard/core/Seq) of the ANS Forth standard.

This word is mentioned in `file.fth` and `t_file.fth`, perhaps this was worked on previously but not finalised?

**Comment by philburk** [comment]
S\" adds the ability to enter escaped strings like "tree\tfrog\r".
A reference implementations is at:
    http://www.forth200x.org/escaped-strings.html

This will need good tests to let's add this after we get the improved testing done. #83

**Comment by MaxBarraclough** [comment]
> S" adds the ability

I think GitHub swallowed a backslash there?

**Comment by philburk** [comment]
You're right. I edited the comment above to use double slash and it looks correct now.
